name: Get project version from Gradle

on:
  workflow_call:
    inputs:
      java_version:
        description: "Java version to run gradle."
        required: false
        type: number
        default: 17
      gradle_args:
        description: "Arguments to be passed to the gradle command line."
        required: false
        type: string
        default: ""
      gradle_module:
        description: "The gradle module to use. Leave blank for root."
        required: false
        type: string

jobs:
  get_version:
    uses: ./.github/workflows/get-gradle-project-version.yml
    with:
      java_version: ${{ inputs.java_version }}
      gradle_args: ${{ inputs.gradle_args }}
      gradle_module: ${{ inputs.gradle_module }}

  publish:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - uses: actions/checkout@v4

      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: v${{ needs.get_version.outputs.version }}
